### ISSUE TITLE
Object not exist...

### ISSUE THREAD

**Issue by momo54** [Chat-Wane/sage-jena#26]
optional query with object that do not exist ??

molli-p@mac-molli-2022 sage-jena-cont % java -jar  sager/target/sager-jar-with-dependencies.jar --database=watdiv10M.jnl -q "select * {?s ?p ?o1 OPTIONAL { ?s ?p <http://www.w3.org/jenexistepas> }}" -l 4 -r
INFO: com.bigdata.util.config.LogUtil: Configure: jar:file:/Users/molli-p/sage-jena-cont/sager/target/sager-jar-with-dependencies.jar!/log4j.properties
WARN	2024-09-12 09:00:39,028	0	com.bigdata.rdf.ServiceProviderHook	[main]	Running.
Path to database: watdiv10M.jnl
SPARQL query: select * {?s ?p ?o1 OPTIONAL { ?s ?p <http://www.w3.org/jenexistepas> }}
ERROR	2024-09-12 09:00:39,331	303	com.bigdata.Banner	[main]	Uncaught exception in thread
fr.gdd.sage.exceptions.NotFoundException: <http://www.w3.org/jenexistepas>
	at fr.gdd.sage.blazegraph.BlazegraphBackend.getId(BlazegraphBackend.java:177)
	at fr.gdd.sage.blazegraph.BlazegraphBackend.getId(BlazegraphBackend.java:41)
	at fr.gdd.sage.generics.CacheId.getId(CacheId.java:25)
	at fr.gdd.sage.generics.Substitutor.substitute(Substitutor.java:28)
	at fr.gdd.sage.generics.Substitutor.substitute(Substitutor.java:20)
	at fr.gdd.sage.sager.iterators.SagerScanFactory.hasNext(SagerScanFactory.java:62)
	at fr.gdd.sage.sager.iterators.SagerOptional.next(SagerOptional.java:103)
	at fr.gdd.sage.sager.iterators.SagerOptional.next(SagerOptional.java:25)
	at fr.gdd.sage.sager.iterators.SagerRoot.hasNext(SagerRoot.java:51)
	at fr.gdd.sage.cli.SagerCLI.main(SagerCLI.java:167)

**Comment by mhoangvslev** [comment]
Shouldn't it be `<http://www.w3.org/jenexistepas>` instead of `http://www.w3.org/jenexistepas`?
